// assets/js/elements/comments/Comments.svelte
<script>
  import {findAllComments, addComment} from '../../api/comments'
  import CommentForm from './CommentForm.svelte'

  export let target

  let comments = null
  let isLoading = false
  let reply = null

  async function loadComments () {
    try {
      const c = await findAllComments(target)
      comments = c.sort((a,b) => b.createdAt - a.createdAt)
    } catch (e) {
      alert(e.detail)
    }
  }

  async function onSubmit (data) {
    isLoading = true
    try {
      const comment = await addComment({target: target, ...data})
      comments = [comment, ...comments]
    } catch (e) {
      alert(e.detail)
    }
    isLoading = false
  }

  function replyTo(comment) {
    reply = comment
  }

  loadComments()
</script>

{#if comments === null}
<div class="comments-loader">
  <spinning-dots></spinning-dots>
</div>
{:else}
  <aside class="comment-area">
    <div class="comments__title">{comments.length} Commentaires</div>

    <CommentForm loading={isLoading} onSubmit={onSubmit}></CommentForm>

    <hr>

    <div class="comment-list">
      {#each comments as comment (comment.id)}
      <div class="comment">
        <img src="{comment.avatar}" alt="" class="comment__avatar">
        <div class="comment__meta">
          <div class="comment__author">{comment.username}</div>
          <div class="comment__actions">
            <a class="comment__date" href="#c{comment.id}">
              <time-ago time="{comment.createdAt}"></time-ago>
            </a>
            <a href="#c{comment.id}" on:click|stopPropagation|preventDefault={() => replyTo(comment)}>Répondre</a>
            <a href="#c{comment.id}">Supprimer</a>
          </div>
        </div>
        <div class="comment__content form-group">
          <textarea is="textarea-autogrow" required  bind:value={comment.content}></textarea>
        </div>
        <div class="full">
          <button class="btn-gradient">Envoyer</button>
        </div>
        <div class="comment__replies">
          {#if reply === comment}
            <CommentForm loading={isLoading} onSubmit={onSubmit}></CommentForm>
          {/if}
        </div>
      </div>
      {/each}
    </div>


  </aside>
{/if}

// assets/elements/comments/Comments.jsx
import { canManage, isAuthenticated } from '/functions/auth.js'
import { Icon } from '/components/Icon.jsx'
import { memo } from 'preact/compat'
import { useCallback, useState, useRef, useEffect, useMemo } from 'preact/hooks'
import { useAsyncEffect } from '/functions/hooks.js'
import { findAllComments, updateComment, deleteComment, addComment } from '/api/comments.js'
import { PrimaryButton, SecondaryButton } from '/components/Button.jsx'
import { Flex } from '/components/Layout.jsx'
import { Field, Loader } from '/components/Form.jsx'
import { scrollTo } from '/functions/animation.js'
import { catchViolations } from '/functions/api.js'

/**
 * Affiche les commentaires associé à un contenu
 *
 * @param {{target: string}} param0
 */
export function Comments ({ target }) {
  const [state, setState] = useState({
    editing: null, // ID du commentaire en cours d'édition
    comments: null, // Liste des commentaires
    focus: null, // Commentaire à focus
    reply: null // Commentaire auquel on souhaite répondre
  })
  const comments = useMemo(() => {
    if (state.comments === null) {
      return null
    }
    return state.comments.filter(c => c.parent === null).sort((a, b) => b.createdAt - a.createdAt)
  }, [state.comments])

  // Trouve les commentaire enfant d'un commentaire
  function repliesFor (comment) {
    return state.comments.filter(c => c.parent === comment.id)
  }

  // On charge les commentaire dès l'affichage du composant
  useAsyncEffect(async () => {
    const comments = await findAllComments(target)
    setState(s => ({ ...s, comments }))
  }, [target])

  // On focalise se focalise sur un commentaire
  useEffect(() => {
    if (focus) {
      scrollTo(document.getElementById('c' + state.focus))
      setState(s => ({ ...s, focus: null }))
    }
  }, [state.focus])

  // On comment l'édition d'un commentaire
  const handleEdit = useCallback(comment => {
    setState(s => ({ ...s, editing: s.editing === comment.id ? null : comment.id }))
  }, [])

  // On met à jour (via l'API un commentaire)
  const handleUpdate = useCallback(async (comment, content) => {
    const newComment = await updateComment(comment.id, content)
    setState(s => ({
      ...s,
      editing: null,
      comments: s.comments.map(c => (c === comment ? newComment : c))
    }))
  }, [])

  // On supprime un commentaire
  const handleDelete = useCallback(async comment => {
    await deleteComment(comment.id)
    setState(s => ({
      ...s,
      comments: s.comments.filter(c => c !== comment)
    }))
  }, [])

  // On répond à un commentaire
  const handleReply = useCallback(comment => {
    setState(s => ({ ...s, reply: comment.parent || comment.id }))
  }, [])
  const handleCancelReply = useCallback(() => {
    setState(s => ({ ...s, reply: null }))
  })

  // On crée un nouveau commentaire
  const handleCreate = useCallback(
    async (data, parent) => {
      data = { ...data, target, parent }
      const newComment = await addComment(data)
      setState(s => ({
        ...s,
        focus: newComment.id,
        reply: null,
        comments: [newComment, ...s.comments]
      }))
    },
    [target]
  )

  // On affiche le chargement en attendant
  if (comments === null) {
    return <Loader />
  }

  // On rend la liste des commentaires
  return (
    <div className='comment-area'>
      <div className='comments__title'>{state.comments.length} Commentaires</div>
      <CommentForm onSubmit={handleCreate} />
      <hr />
      <div className='comment-list'>
        {comments.map(comment => (
          <Comment
            key={comment.id}
            comment={comment}
            editing={state.editing === comment.id}
            onEdit={handleEdit}
            onUpdate={handleUpdate}
            onDelete={handleDelete}
            onReply={handleReply}
          >
            {repliesFor(comment).map(reply => (
              <Comment
                key={reply.id}
                comment={reply}
                editing={state.editing === reply.id}
                onEdit={handleEdit}
                onUpdate={handleUpdate}
                onDelete={handleDelete}
                onReply={handleReply}
              />
            ))}
            {state.reply === comment.id && (
              <CommentForm onSubmit={handleCreate} parent={comment.id} onCancel={handleCancelReply} />
            )}
          </Comment>
        ))}
      </div>
    </div>
  )
}

/**
 * Affiche un commentaire
 */
const Comment = memo(function ({ comment, editing, onEdit, onUpdate, onDelete, onReply, children, replies }) {
  const anchor = '#c' + comment.id
  const canEdit = canManage(comment.userId)
  const className = ['comment']
  const textarea = useRef(null)
  const [loading, setLoading] = useState(false)
  let content = <div>{comment.content}</div>

  function handleEdit (e) {
    e.preventDefault()
    onEdit(comment)
  }

  async function handleUpdate (e) {
    e.preventDefault()
    setLoading(true)
    await onUpdate(comment, textarea.current.value)
    setLoading(false)
  }

  async function handleDelete (e) {
    e.preventDefault()
    if (confirm('Voulez vous vraiment supprimer ce commentaire ?')) {
      setLoading(true)
      await onDelete(comment)
    }
  }

  function handleReply (e) {
    e.preventDefault()
    onReply(comment)
  }

  // On focus automatiquement le champs quand il devient visible
  useEffect(() => {
    if (textarea.current) {
      textarea.current.focus()
    }
  }, [editing])

  if (editing) {
    content = (
      <>
        <textarea is='textarea-autogrow' ref={textarea} defaultValue={comment.content} />
        <Flex>
          <PrimaryButton onClick={handleUpdate}>Modifier</PrimaryButton>
          <SecondaryButton onClick={handleEdit}>Annuler</SecondaryButton>
        </Flex>
      </>
    )
  }
  if (loading) {
    className.push('is-loading')
  }

  return (
    <div className={className.join(' ')} id={'c' + comment.id}>
      <img src={comment.avatar} alt='' className='comment__avatar' />
      <div className='comment__meta'>
        <div className='comment__author'>{comment.username}</div>
        <div className='comment__actions'>
          <span className='comment__date'>
            <time-ago time={comment.createdAt} />
          </span>
          <a href={anchor} onClick={handleReply}>
            <Icon name='reply' />
            Répondre
          </a>
          {canEdit && (
            <a href={anchor} onClick={handleEdit}>
              <Icon name='edit' />
              Editer
            </a>
          )}
          {canEdit && (
            <a href={anchor} onClick={handleDelete}>
              <Icon name='trash' />
              Supprimer
            </a>
          )}
        </div>
      </div>
      <div className='comment__content form-group stack'>{content}</div>
      <div className='comment__replies'>{children}</div>
    </div>
  )
})

/**
 * Formulaire de commentaire
 * @params {{onSubmit: function, parent: number}} props
 */
function CommentForm ({ onSubmit, parent, onCancel = null }) {
  const [loading, setLoading] = useState(false)
  const [errors, setErrors] = useState({})
  const ref = useRef(null)

  const handleSubmit = useCallback(
    async function (e) {
      const form = e.target
      e.preventDefault()
      setLoading(true)
      const [_, errors] = await catchViolations(onSubmit(Object.fromEntries(new FormData(form)), parent))
      if (errors) {
        setErrors(errors)
      } else {
        form.reset()
      }
      setLoading(false)
    },
    [onSubmit]
  )

  const handleCancel = function (e) {
    e.preventDefault()
    onCancel()
  }

  useEffect(
    function () {
      if (parent && ref.current) {
        scrollTo(ref.current)
      }
    },
    [parent]
  )

  return (
    <form className='grid' onSubmit={handleSubmit} ref={ref}>
      {!isAuthenticated() && (
        <>
          <Field name='username' defaultValue='John' error={errors.username}>
            Nom d'utilisateur
          </Field>
          <Field name='email' type='email' defaultValue='john@doe.fr' required error={errors.email}>
            Email
          </Field>
        </>
      )}
      <div className='full'>
        <Field type='textarea' name='content' defaultValue='Votre message ici ' error={errors.content} required>
          Votre message
        </Field>
      </div>
      <Flex className='full'>
        <PrimaryButton type='submit' loading={loading}>
          Envoyer
        </PrimaryButton>
        {onCancel && <SecondaryButton onClick={handleCancel}>Annuler</SecondaryButton>}
      </Flex>
    </form>
  )
}
